## Reference: https://github.com/helm/chart-releaser
index-path: "./index.yaml"

# PGP signing
sign: true
key: Caju Helm maintainers
# keyring:          # Set via env variable CR_KEYRING
# passphrase-file:  # Set via env variable CR_PASSPHRASE_FILE
